server:
  port: 9000
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:h2:mem:cmisdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never # always, embedded
logging:
  level:
    root: INFO
    ch.elbernito.cmis.mock: DEBUG

cmis:
  repositories:
    - repositoryId: repo1
      repositoryName: InMemoryRepo
      vendorName: SugarElHoney
      productName: CMIS Mock
      productVersion: "1.0.0"
      rootFolderId: root
      cmisVersionSupported: "1.2"
      capabilities:
        allVersionsSearchable: true
        capabilityQueries: true
        capabilityJoin: true
        capabilityCancelCheckOut: true
        capabilityMultifiling: true
        capabilityUnfiling: true
        capabilityVersionSpecificFiling: true
      aclCapability:
        supportedPermissions: basic
        aclPropagation: true
    # → hier bei Bedarf weitere Repositories hinzufügen