server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:mem:cmisdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: info
    ch.elbernito.cmis.mock: debug
    org:
      hibernate: OFF
      hibernate.SQL: OFF
      hibernate.type.descriptor.sql: OFF
      hibernate.stat: OFF
      hibernate.tool.hbm2ddl: OFF
    org.springframework.orm.jpa: OFF
    org.springframework.transaction: OFF
    com.zaxxer.hikari: OFF

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
