spring:
  datasource:
    url: jdbc:h2:mem:cmisdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop   # Oder update, 'create', 'create-drop', je nach Bedarf
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: never # wenn die data.sql und schema.sql geladen werden sollen. aber achtung das muss dann passen!

server:
  port: 9000

logging:
  level:
    root: warn
    ch.elbernito.cmis.mock: DEBUG
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: off

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

